### ISSUE TITLE
Claim to get GitHub Actions working with coveralls + Python

### ISSUE THREAD

**Issue by ttimbers** [ttimbers/foocat#1]
https://github.com/coverallsapp/github-action/issues/4#issuecomment-570879494

**Comment by ttimbers** [comment]
went with codecov instead, much smoother!

**Comment by jlumbroso** [comment]
@ttimbers Thanks for the advice. I just ditched coveralls for codecov, and wish I had known about this hours ago! And the interface is nicer too!!
